package main

import (
	"crypto/rand"
	"fmt"
	"math/big"
	//"math/rand"
	//"time"
)

func main() {

	fmt.Println("Welcome to golang maths")
	//var myNumberOne int = 2 // this is of type int
	//var myNumberTwo float64 = 3.5 // this is of type float

	//fmt.Println("The sum is: ", myNumberOne + int(myNumberTwo)) // this isn't valid bcoz
	//when you convert myNumberTwo into integer it becomes 3 from 3.5 so the .5 is neglected and thats not quite right

	//RANDOM NUMBER
	//1.random number generated by the math
	//2.Cryptography algorithm gives more surety about a true random number
	//rand.Seed(time.Now().UnixMilli()) // before the go 1.20.0 update the seed was required for different random numbers
	//fmt.Println(rand.Intn(5))

	//random no from crypto

	myRandomnum, _ := rand.Int(rand.Reader, big.NewInt(5)) 
	fmt.Println(myRandomnum)

}
